# -*- coding: utf-8 -*-
"""RandIndex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JUywXKgQUDbI_nLyGH1S62eMoccWFy6R
"""

import pandas as pd
import numpy as np
import scipy.cluster.hierarchy as sch
data = pd.read_csv('/content/Mall_Customers.csv')
data.set_index('CustomerID',inplace=True)
data['Gender'].replace(['Female','Male'],[0,1],inplace=True)

def rand_index(c1,c2):
  n=len(c1)
  alpha , beta, gamma, delta = 0,0,0,0
  for i in range(n-1):
    for j in range(i+1,n):
      if ((c1[i]==c1[j]) & (c2[i]==c2[j])):
        alpha += 1
      elif((c1[i]!=c1[j]) & (c2[i]!=c2[j])):
        beta += 1
      elif((c1[i]==c1[j]) & (c2[i]!=c2[j])):
        gamma += 1
      elif((c1[i]!=c1[j]) & (c2[i]==c2[j])):
        delta += 1
  #print(alpha,beta,gamma,delta)
  return (alpha+beta)/(alpha+beta+gamma+delta)

c1 = np.array([1,1,1,2,2,2,3,3])
c2 = np.array([2,2,1,1,1,1,2,3])
print("Rand index is: ",rand_index(c1,c2))

Z = sch.linkage(data,method='complete')
#dend = sch.dendrogram(Z)
num__of_clusters = 2
clusters = sch.fcluster(Z,num__of_clusters,criterion='maxclust')

import matplotlib.pyplot as plt
gap = []
for i in range(1,30):
        cluster1 = sch.fcluster(Z,i,criterion='maxclust')
        cluster2 = sch.fcluster(Z,i+1,criterion='maxclust')
        randIndex = rand_index(cluster1,cluster2)
        gap = np.append(gap,randIndex)
        #print(i,randIndex)
print(gap)
plt.plot(1-gap)